# OpenLiteSpeed Isolated Configuration for {{DOMAIN}}
# Generated by wp-isolate on {{TIMESTAMP}}

extprocessor lsphp_{{DOMAIN_CLEAN}} {
  type                    lsapi
  address                 uds://tmp/lshttpd/lsphp_{{DOMAIN_CLEAN}}.sock
  maxConns                {{MAX_CONNS}}
  env                     LSAPI_AVOID_FORK=1
  initTimeout             60
  retryTimeout            0
  persistConn             1
  pcKeepAliveTimeout      30
  respBuffer              0
  autoStart               1
  path                    {{LSPHP_PATH}}
  backlog                 50
  instances               1
  extUser                 {{USER}}
  extGroup                {{USER}}
  runOnStartUp            1
  priority                0
  memSoftLimit            {{MEM_SOFT_LIMIT}}
  memHardLimit            {{MEM_HARD_LIMIT}}
  procSoftLimit           {{PROC_SOFT_LIMIT}}
  procHardLimit           {{PROC_HARD_LIMIT}}
}

scripthandler {
  add lsapi:lsphp_{{DOMAIN_CLEAN}} php
}

phpIniOverride {
  php_value open_basedir "{{DOCROOT}}/:/tmp/:/dev/urandom"
  php_value session.save_path "/tmp"
  php_value upload_tmp_dir "/tmp"
}

# L7 Anti-DDoS and Request Throttling
perClientConnLimit        {{PER_CLIENT_CONN_LIMIT}}
dynReqPerSec              {{DYN_REQ_PER_SEC}}
outBandwidth              0
inBandwidth               0
blockBadReq               1
